/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyectologinzapateria;


import proyectologinzapateria.Clases.Encoder;
import javax.swing.JOptionPane;
import libreriaconexion.ConexionMySQL;
import java.sql.SQLException;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.ImageIcon;



/**
 *  Aqui se usaran los metodos de busqueda de la libreria
 *  Lo meteremos en iun if para que:
 *  si el registro existe (usuario) abra la ventana principal (productos)
 *  si no existe, nos muestre las excepciones
 * 
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }
    
    public void iniciarSesion(){
    
        String correo = txtCorreo.getText().trim();
        String contraseña = new String(pswContraseña.getPassword());
        String conEncriptada = Encoder.encriptar(contraseña);


        if (correo.isEmpty() || contraseña.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor, ingresa tu correo y contraseña.");
            return;
        }

        boolean conectado = ConexionMySQL.conectar("3306", "zapateria", "root", "71b748ad9b");
        if (!conectado) {
            JOptionPane.showMessageDialog(this, "No se pudo conectar con la base de datos.");
            return;
        }


        String sql = "SELECT Rol FROM usuarios WHERE Correo = ? AND Contraseña = ?";

            try (PreparedStatement ps = ConexionMySQL.getConexion().prepareStatement(sql)) {
                ps.setString(1, correo);
                ps.setString(2, conEncriptada);

                ResultSet rs = ps.executeQuery();

                if (rs.next()) {
                        String rol = rs.getString("Rol");

                        if ("Administrador".equalsIgnoreCase(rol)) {
                            JOptionPane.showMessageDialog(this, "Bienvenido Administrador.");
                            
                            MenuPrincipal menu = new MenuPrincipal();
                            menu.setVisible(true); 
                            
                        } else {
                            JOptionPane.showMessageDialog(this, "Bienvenido Cajero.");
                            Cajero cajero = new Cajero();
                            cajero.setVisible(true); // Abre el frame Publico
                        }

                        this.dispose(); // Cierra la ventana de login

                    } else {
                        JOptionPane.showMessageDialog(this, "Correo o contraseña incorrectos.");
                    }

                } catch (SQLException e) {
                    JOptionPane.showMessageDialog(this, "Error al iniciar sesión: " + e.getMessage());
                }
        
    }
    
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnVisitante = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        pswContraseña = new javax.swing.JPasswordField();
        btnIngresar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        btnMostrarContraseña = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        btnRegistarse = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(0, 0));
        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesInterfaz/tacon3.png"))); // NOI18N
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 260, 70));

        jLabel3.setFont(new java.awt.Font("Perpetua Titling MT", 1, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("VANILLA UNICORN");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 260, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesInterfaz/fondo.jpeg"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 260, 480));

        btnVisitante.setText("VISITANTE");
        btnVisitante.setPreferredSize(new java.awt.Dimension(86, 35));
        btnVisitante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVisitanteActionPerformed(evt);
            }
        });
        jPanel2.add(btnVisitante, new org.netbeans.lib.awtextra.AbsoluteConstraints(274, 431, -1, -1));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("INICIAR SESIÓN");
        jLabel4.setToolTipText("");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 460, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesInterfaz/correo.png"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 234, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesInterfaz/password.png"))); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 291, -1, -1));

        txtCorreo.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtCorreo.setPreferredSize(new java.awt.Dimension(70, 30));
        jPanel1.add(txtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(109, 234, 250, -1));

        pswContraseña.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pswContraseña.setMinimumSize(new java.awt.Dimension(70, 30));
        jPanel1.add(pswContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(109, 291, 250, 32));

        btnIngresar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnIngresar.setText("INGRESAR");
        btnIngresar.setPreferredSize(new java.awt.Dimension(30, 100));
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });
        jPanel1.add(btnIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 350, 96, 40));

        btnSalir.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnSalir.setText("SALIR");
        btnSalir.setPreferredSize(new java.awt.Dimension(30, 100));
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        jPanel1.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 350, 86, 40));

        btnMostrarContraseña.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesInterfaz/ojo_ver.png"))); // NOI18N
        btnMostrarContraseña.setToolTipText("");
        btnMostrarContraseña.setBorder(null);
        btnMostrarContraseña.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMostrarContraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarContraseñaActionPerformed(evt);
            }
        });
        jPanel1.add(btnMostrarContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 290, -1, -1));

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesInterfaz/user1.png"))); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 60, 450, -1));

        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(266, 0, 436, -1));

        btnRegistarse.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnRegistarse.setText("REGISTRARSE");
        btnRegistarse.setPreferredSize(new java.awt.Dimension(35, 100));
        btnRegistarse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistarseActionPerformed(evt);
            }
        });
        jPanel2.add(btnRegistarse, new org.netbeans.lib.awtextra.AbsoluteConstraints(586, 432, 108, 34));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed
      
        iniciarSesion();
        
    }//GEN-LAST:event_btnIngresarActionPerformed

    private void btnRegistarseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistarseActionPerformed
        
        //Aqui añadimos un if, verificamos el rol del usuario ingresado
        //Si es administrador, se mostrara el frame Productos
        //Si es usuario, se mostrara el frame de publico
        
        Registro registro = new Registro();
        registro.setVisible(true);
        //this.setVisible(false);
    }//GEN-LAST:event_btnRegistarseActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnMostrarContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarContraseñaActionPerformed

        if (pswContraseña.getEchoChar() == '*') { // '\u2022' es el carácter de punto negro
            pswContraseña.setEchoChar((char) 0); // Muestra la contraseña
            
        } else {
            pswContraseña.setEchoChar('*'); // Oculta la contraseña

        }

    }//GEN-LAST:event_btnMostrarContraseñaActionPerformed

    private void btnVisitanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVisitanteActionPerformed

        Visitante visitante =  new Visitante();
        visitante.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_btnVisitanteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIngresar;
    private javax.swing.JButton btnMostrarContraseña;
    private javax.swing.JButton btnRegistarse;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnVisitante;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField pswContraseña;
    private javax.swing.JTextField txtCorreo;
    // End of variables declaration//GEN-END:variables
}
